MONITOR apc600@localhost 1 upsmon_local CHANGEME_GENERATE_RANDOM master

MINSUPPLY 1
SHUTDOWNCMD "/srv/shared/bin/cluster-shutdown.sh"

NOTIFYCMD /srv/shared/bin/ups-notify.sh
NOTIFYFLAG ONLINE    SYSLOG+EXEC
NOTIFYFLAG ONBATT    SYSLOG+EXEC
NOTIFYFLAG LOWBATT   SYSLOG+EXEC
NOTIFYFLAG SHUTDOWN  SYSLOG+EXEC

FINALDELAY 10
DEADTIME 15
